### ISSUE TITLE
About preprocessing TIMIT dataset

### ISSUE THREAD

**Issue by harouwu** [TimovNiedek/timit_tf#1]
Hi,

I just start touching ASR and I find your code very interesting. When I want to run it on TIMIT dataset from our school, I found that the TIMIT dataset I have is the original version with just sphere WAV, phn, txt, wrd files.

I managed to convert sphere WAV to mfcc. I want to know how does your train/test data folder look like?

Should I put all phn and npy(mfcc) in the same folder? How should I name them? Because I saw you manipulated file name to get speaker info.

Thanks!

**Comment by TimovNiedek** [comment]
Hello,

Great to see that you are interested. I have created this software as a part of my Bachelor Thesis project, which can be found [here](http://www.cs.ru.nl/bachelorscripties/2016/Timo_van_Niedek___4326164___Phonetic_Classification_in_TensorFlow.pdf). If you are interested, I recommend taking a look since it should answer many questions.

As for the inputs, the MFCC data was generated by my supervisor using Kaldi's 's5' recipe. The resulting files were .txt files in one tar, where each file was named '<speaker name>_<dialect region><speaker name><sentence id>.txt'. To match these files with the phn files in TIMIT, I had to match these filenames with the folder structure of TIMIT. This code can be found in convert_data.py .

Since you have generated the MFCCs yourself, it might be easier to put the MFCC files in the same folders as the TIMIT data and modify the convert_data.py file to match the files more easily. In particular the match_data function can be simplified a lot if the files are where they should be. Important is that the other scripts recieve a pickle file as input, which is generated in the main function of convert_data.py .

The substitute_phones.py file needs to be run first to convert the phones in the phn files to the names that I have used. This script creates a 'phones' pickle, which is used in convert_data.py

I hope this will help. If you have any other questions feel free to ask!

**Comment by anirbanbhowmick15** [comment]
Hello, Timo van,
Thanks for sharing your code. I am also using this code on TIMIT database. One thing I want to know that in the substitute_phones.py code the folder path is absolute TIMIT path or I have to run it separately for TRAIN and TEST set. Actually, I want to know the exact path.

Thanks!

**Comment by Syluyi** [comment]
Hi Timo,

I found this code through your bachelor thesis. It was really helpful to understand ASR better. 

I'm currently trying to use your code as a basis to analyze the CGN dataset. But I can't seem to figure out what your input files look like. I could find the original .phn files for Timit, but I'm not sure about the other input files like the phones.pickle. Could you give more information on what your input data looks like? Or do you have example input so I can run the program myself?

Thank you,
Nikki

**Comment by TimovNiedek** [comment]
Attachment available until August 05, 2017.
Hello Nikki,

Good to hear that my code was useful. The TIMIT dataset has some labels that are difficult to use as-is.
Many of the phonetic labels are grouped together as one phone during training. There are 61 unique phones in the original data set, that are reduced to 48. Then, during testing they are further reduced. I encourage you to take a look at my bachelor's thesis in which these details are explained:

http://www.cs.ru.nl/bachelorscripties/2016/Timo_van_Niedek___4326164___Phonetic_Classification_in_TensorFlow.pdf

The phones.pickle is simply a list of training phones used. It is generated by runnning substitute_phones.py with:

python substitute_phones.py <train folder> --startendsil foldings61-48.json

You should also run convert_data.py before running the dnn/lstm scripts. This creates the train_data.pickle and test_data.pickle files, which are used as input for training/testing.

I hope this helps, I realize that the project setup is quite confusing due to the different preprocessing steps.
If you have any other questions, let me know.

Best,
Timo

On Jul 05, 2017, at 09:49 PM, Nikki van der Gouw <notifications@github.com> wrote:

Hi Timo,
I found this code through your bachelor thesis. It was really helpful to understand ASR better.
I'm currently trying to use your code as a basis to analyze the CGN dataset. But I can't seem to figure out what your input files look like. I could find the original .phn files for Timit, but I'm not sure about the other input files like the phones.pickle. Could you give more information on what your input data looks like? Or do you have example input so I can run the program myself?
Thank you,
Nikki

**Comment by Syluyi** [comment]
Hello Timo,

Thank you for your quick and elaborate response! 
It's really helpful. 

Best,
Nikki

**Comment by abbasrazaali** [comment]
Hi Timo, can you please share timid-txt.tar.gz file again? thanks

**Comment by coax1d** [comment]
Hi Timo the link you provided earlier for syluyi expired the one for the MFCC's could you resend that link or send it to me somehow having a bear of a time trying to use kaldi to extract the MFCC's

**Comment by wuqiangch** [comment]
@TimovNiedek  Can't open the link.

**Comment by TimovNiedek** [comment]
@coax1d @wuqiangch I cannot provide the link anymore as it has expired and I do not have the files anymore. If you want to get MFCC features from audio, I can recommend the [python_speech_features](https://github.com/jameslyons/python_speech_features) module, which is very easy to use.

**Comment by wuqiangch** [comment]
@TimovNiedek ,How  to set winlen(25ms) and winstep(15ms)? A frame length of 10 ms is used in your thesis.

**Comment by TimovNiedek** [comment]
@wuqiangch The code for my thesis did not include feature extraction. Are you referring to the python_speech_features package? If so, I would redirect you to their repository (linked before), especially the readme file.

**Comment by wuqiangch** [comment]
@TimovNiedek How to deal with the test labels? 48 or 39? In your code ，it is 48,not 39.
